### ISSUE TITLE
No module named defaults

### ISSUE THREAD

**Issue by asivaneswaran** [jaredly/django-feedback#11]
Environment:

Request Method: GET
Request URL: http://localhost:8000/teams/arsenal-2/

Django Version: 1.6.1
Python Version: 2.7.6
Installed Applications:
('grappelli.dashboard',
 'grappelli',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.sites',
 'django.contrib.comments',
 'localflavor',
 'smuggler',
 'south',
 'activelink',
 'reversion',
 'autoslug',
 'qrcode',
 'ajax_select',
 'django_object_actions',
 'imagekit',
 'django_notify',
 'mptt',
 'sekizai',
 'sorl.thumbnail',
 'wiki',
 'wiki.plugins.attachments',
 'wiki.plugins.notifications',
 'wiki.plugins.images',
 'wiki.plugins.macros',
 'feedback',
 'managesite',
 'managelayerslider',
 'blog',
 'acpkinballmanageleague',
 'acpkinballmanageteams',
 'acpkinballmanageevents',
 'acpkinballmanagemembers')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "C:\Python27\lib\site-packages\django\core\handlers\base.py" in get_response
  101.                 resolver_match = resolver.resolve(request.path_info)
File "C:\Python27\lib\site-packages\django\core\urlresolvers.py" in resolve
  318.             for pattern in self.url_patterns:
File "C:\Python27\lib\site-packages\django\core\urlresolvers.py" in url_patterns
  346.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "C:\Python27\lib\site-packages\django\core\urlresolvers.py" in urlconf_module
  341.             self._urlconf_module = import_module(self.urlconf_name)
File "C:\Python27\lib\site-packages\django\utils\importlib.py" in import_module
  40.         __import__(name)
File "C:\Users\Ara\Documents\Sites\kinball\kinball\urls.py" in <module>
  94.     url(r'^feedback/', include('feedback.urls')),
File "C:\Python27\lib\site-packages\django\conf\urls\__init__.py" in include
  26.         urlconf_module = import_module(urlconf_module)
File "C:\Python27\lib\site-packages\django\utils\importlib.py" in import_module
  40.         __import__(name)
File "C:\Python27\lib\site-packages\feedback\urls.py" in <module>
  1. from django.conf.urls.defaults import *

Exception Type: ImportError at /teams/arsenal-2/
Exception Value: No module named defaults

**Comment by PetrDlouhy** [comment]
Django-feedback should now work up o Django 1.8. Closing the issue. In case of any problems, please reopen or write new issue.
