### ISSUE TITLE
KeyError on GET request

### ISSUE THREAD

**Issue by orblivion** [jaredly/django-feedback#17]
If you visit /feedback/ajax/* you get a key error in views.py:

`post = kwargs['data'].copy()`

`'data'` doesn't seem to exist in GET requests. This shouldn't even be getting GET requests, I imagine, so you should probably just return a "method not allowed" error upfront.

**Comment by jaredly** [comment]
good point. I'm not doing any django anymore, but I'd be happy to accept a PR :)

**Comment by PetrDlouhy** [comment]
This has been fixed by 0a0bd154. Can you test?
